fix: avoid multiple segment identify calls
openedx/frontend-platform pull request #458
Opened 2023-03-20 12:51 UTC by shahbaz-arbisoft

This PR adds a check to avoid multiple identify calls to the segment.

**Context:**

In Authn, a user has an anonymous id in all segment events until the user is authenticated. A user is moved to the welcome page after registration and we want to fire a segment identify call on the welcome page because the user is now authenticated. But the identify call is not fired until the user reloads the page manually. So we are explicitly calling `identifyAuthenticatedUser` in the welcome page so that the user has its actual user ID in all the segment events.

This works fine and identify call is fired with the user ID on the welcome page.

**Issue:**

The issue is when a user reloads the page, there are 3 identify calls being fired.

1. The automatically identify call due to reloading.
2. Our explicit identify call from `useEffect` which has `authenticatedUser` as a dependency which we get from the 
`getAuthenticatedUser` function.
3. We are also using `hydrateAuthenticatedUser` to attach some additional user attributes to authenticated User, which changes the `authenticatedUser` object causing `useEffect` to call `identifyAuthenticatedUser` again.

We want to avoid these multiple calls and we noticed that we have a `hasIdentifyBeenCalled` flag in `frontend-platform`, so we are using this flag in the `identifyAuthenticatedUser` function to avoid multiple identify calls.

2023-03-20 13:58 UTC, davidjoy reviewed
@robrap Do we know of any reason why we might want to call identify more than once?  If not, this seems fine to me.  @shahbaz-arbisoft, I would perhaps suggest we do the same check in identifyAnonymousUser for parity.

2023-03-20 14:56 UTC, shahbaz-arbisoft commented
@davidjoy PR updated.

2023-03-20 15:35 UTC, davidjoy requested changes
Oh, right, I forgot - we should add tests that prove we're not double-calling identify now.

2023-03-27 11:31 UTC, shahbaz-arbisoft commented
@davidjoy I have added tests for it, kindly review them.

2023-03-28 00:37 UTC, merged