docs: Update the maintainer.
openedx/frontend-platform pull request #722
Opened 2024-07-19 20:03 UTC by feanil

Adolfo, Brian and Braden have been defacto maintainers here just make
that official.

2024-07-19 20:15 UTC, brian-smith-tcril approved these changes
:+1: from me

2024-07-22 19:19 UTC, arbrandes approved these changes
No objections!

2024-07-22 19:58 UTC, kdmccormick requested changes

2024-07-22 19:58 UTC, kdmccormick commented on catalog-info.yaml
> +  owner: "group:frontend-all"
```suggestion
  owner: "group:committers-frontend"
```

I changed the team name a few months ago: https://github.com/orgs/openedx/teams/committers-frontend

2024-07-24 14:52 UTC, merged